

devices([
  "iPhone 4s",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus",
])

languages([
  "en-US"
])

project "loginredirect_ios_source-noads/AppsMobileCompany.xcodeproj"
app_identifier "com.mae.test.app5714b67dad01f"
scheme "FabricUITests"
configuration "Debug"

number_of_retries 2
reinstall_app true
stop_after_first_error true
clear_previous_screenshots true
