

devices([
  "iPhone 4s",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus",
])

languages([
  "en-US"
])

project "chat_ios_source/AppsMobileCompany.xcodeproj"
app_identifier "com.portableappsstore.app573ee717152e8"
#scheme "FabricUITests"
#configuration "Debug"

#number_of_retries 2
#reinstall_app true
#stop_after_first_error true
#clear_previous_screenshots true
# Where should the resulting screenshots be stored?
screenshots_path "./screenshots"
